### ISSUE TITLE
Ich kann den Bot nicht starten.

### ISSUE THREAD

**Issue by UnlegitHax** [zekroTJA/yuri#1]
Hallo zekro!
Ich habe hier ein kleines Problemchen mit `yuri` und zwar wenn ich versuche `yuri` zu starten kommt das: 
http://cdn.unlgt.ml/imgs/2018-06-05_18-01-29.png 
Ich wüsste jetzt nicht wie ich das beheben kann. Die `config.json` habe ich schon bearbeitet und auch `npm install` in der Konsole ausgeführt.

**Comment by zekroTJA** [comment]
Sollte gefixt sein ;)
https://travis-ci.org/zekroTJA/yuri/builds/388621654
