### ISSUE TITLE
Sound Command funktioniert nicht

### ISSUE THREAD

**Issue by UnlegitHax** [zekroTJA/yuri#2]
Ich hab FFMPEG auf meinem PC. Auch schon `npm install` gemacht und den Bot mit der gefixten Version gestartet aber jetzt tritt ein neuer Error auf: [Klick mich um zu sehen wie das ganze aussieht](http://cdn.unlgt.ml/imgs/2018-06-08%2015-42-08.mp4)

**Comment by zekroTJA** [comment]
Ich gehe mal davon aus, dass auf dem Host-PC ein Linux-System läuft.

Ich habe 1 zu 1 die Schritte des [Setups](https://github.com/zekroTJA/yuri#setup) befolgt und habe keinerlei Probleme. [[Video]](https://zekro.de/sharing/2018-06-09_11-51-22.mp4)
> Host: Ubuntu 17.10 x64; Node v6.11.4; NPM v3.5.2

Wurden alle Dependencies auch richtig heruntergeladen und compiliert? 
Kannst du das ganze vielleicht auch nochmal mit dem [zekroBot2](https://github.com/zekroTJA/zekroBot2/wiki/Instalation-(Self-Hosting)) testen? Der benutzt die selbe Audio-Library.
Ansonsten vielleicht nochmal mit anderen Discord Music-Bots testen die auf Node laufen und die selbe Dependency nutzen.
